version: '2'
services:
  postgres:
    image: postgres:9.5.4
  app:
    build:
      context: .
    volumes:
      - .:/home/rails/app
  nginx:
    image: nginx:1.11.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
